apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndtech-sapper
spec:
  replicas: 0
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ndtech-sapper
  template:
    metadata:
      labels:
        app: ndtech-sapper
    spec:
      containers:
      - name: ndtech-sapper
        image: 22ndtech/ndtech-sapper:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"